
import java.io.FileWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Serra
 */
public class DeliveryPage extends javax.swing.JFrame {

    /**
     * Creates new form DeliveryPage
     */
    User user;
    public DeliveryPage(User user) {
        this.user = user;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_cardNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_nameOnCard = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_month = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_ccv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        btn_complite = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Card Informations");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Card Number :");

        txt_cardNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Name on the Card :");

        txt_nameOnCard.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Month / Year :");

        txt_month.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("/");

        txt_year.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("CCV :");

        txt_ccv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Address Informations");

        txt_address.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btn_complite.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_complite.setText("Complite");
        btn_complite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compliteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_back))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_nameOnCard, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_ccv, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_cardNumber)))
                            .addComponent(txt_address))))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_complite)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btn_back)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_nameOnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_cardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_ccv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txt_address, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btn_complite)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        ShoppingCartPage sc = new ShoppingCartPage(user);
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_compliteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compliteActionPerformed
        // TODO add your handling code here:
        String cardNumber = txt_cardNumber.getText();
        String month = txt_month.getText();
        String year = txt_year.getText();
        String cvv = txt_ccv.getText();
        String nameSurname = txt_nameOnCard.getText();
        String address = txt_address.getText();

        String cardNumberRegex = "[0-9]{16}";
        String monthRegex = "(0[1-9]|1[0-2])";
        String yearRegex = "[0-9]{2}";
        String cvvRegex = "[0-9]{3}";
        String nameRegex = "[a-zA-ZçÇğĞıİöÖşŞüÜ]+( [a-zA-ZçÇğĞıİöÖşŞüÜ]+)*";
        
        if (!cardNumber.matches(cardNumberRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid card number. Please enter a valid card number.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!month.matches(monthRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid month information. Please enter a valid month.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
         if (!year.matches(yearRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid year information. Please enter a valid year.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!cvv.matches(cvvRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid CV. Please enter a valid CVV.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!nameSurname.matches(nameRegex)) {
            JOptionPane.showMessageDialog(null, "Invalid last name. Please enter a valid first and last name.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Order order = new Order(user.getId(), address);
        boolean isOrderSaved = OrderDatabaseManager.saveOrder(order);
        if (isOrderSaved) {
            List<ShoppingCartItem> cartItems = ShoppingCartDatabaseManager.getUserShoppingCart(user.getId());

            StringBuilder orderDetails = new StringBuilder();
            orderDetails.append("Order Details:\n");
            orderDetails.append("Order Id: " + order.getOrderId() + "\n");
            orderDetails.append("Email: " + user.getEmail() + "\n");
            orderDetails.append("Address: " + order.getAddress() + "\n");
            orderDetails.append("Products:\n");

            BigDecimal totalPrice = BigDecimal.ZERO;
            for (ShoppingCartItem item : cartItems) {
                OrderedItem orderedItem = new OrderedItem(0, order.getOrderId(), item.getQuantity(), item.getProduct().getPrice());
                OrderDatabaseManager.saveOrderedItem(orderedItem);
    
                BigDecimal itemTotalPrice = item.getProduct().getPrice().multiply(BigDecimal.valueOf(item.getQuantity()));
                orderDetails.append("- " + item.getProduct().getName() + ": " + item.getQuantity() + " pcs, total price: " + itemTotalPrice + "\n");
    
                totalPrice = totalPrice.add(itemTotalPrice);
                }

            orderDetails.append("Total price: " + totalPrice);

            JOptionPane.showMessageDialog(null, orderDetails.toString());
            JOptionPane.showMessageDialog(null, "Order saved successfully");
           

            boolean isCartCleared = ShoppingCartDatabaseManager.clearShoppingCart(user.getId());
            if (isCartCleared) {
                JOptionPane.showMessageDialog(null, "Basket cleared successfully");
            } else {
                JOptionPane.showMessageDialog(null, "An error occurred while clearing the basket");
            }
        } else {
            JOptionPane.showMessageDialog(null, "An error occurred while saving the order");
        }

        ShoppingPage m = new ShoppingPage(this.user);
        m.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btn_compliteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliveryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_back;
    private javax.swing.JToggleButton btn_complite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_cardNumber;
    private javax.swing.JTextField txt_ccv;
    private javax.swing.JTextField txt_month;
    private javax.swing.JTextField txt_nameOnCard;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
